package uk.co.dancingganesh.pocketvedas;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class bool {
        public static final int isTablet = 0x7f050000;
    }

    public static final class drawable {
        public static final int bookmark_plain = 0x7f020000;
        public static final int bookmark_star = 0x7f020001;
        public static final int ic_action_search = 0x7f020002;
        public static final int ic_launcher = 0x7f020003;
    }

    public static final class id {
        public static final int aboutWebView = 0x7f090000;
        public static final int gridView1 = 0x7f090001;
        public static final int pager = 0x7f090002;
        public static final int bookmark_icon = 0x7f090003;
        public static final int bookmark_verse = 0x7f090004;
        public static final int bkmk_description = 0x7f090005;
        public static final int bookmark_description = 0x7f090006;
        public static final int bookmark_dynamic = 0x7f090007;
        public static final int verse_name = 0x7f090008;
        public static final int match_found = 0x7f090009;
        public static final int seekBarPrefUnitsRight = 0x7f09000a;
        public static final int seekBarPrefValue = 0x7f09000b;
        public static final int seekBarPrefUnitsLeft = 0x7f09000c;
        public static final int seekBarPrefBarContainer = 0x7f09000d;
        public static final int seekBarPrefSeekBar = 0x7f09000e;
        public static final int menu_settings = 0x7f09000f;
        public static final int menu_about = 0x7f090010;
        public static final int menu_bookmarks = 0x7f090011;
        public static final int menu_search = 0x7f090012;
        public static final int menu_add_bookmark = 0x7f090013;
        public static final int remove_item = 0x7f090014;
    }

    public static final class layout {
        public static final int activity_about = 0x7f030000;
        public static final int activity_bookmarks = 0x7f030001;
        public static final int activity_books = 0x7f030002;
        public static final int activity_reading = 0x7f030003;
        public static final int activity_search = 0x7f030004;
        public static final int bookmark_item = 0x7f030005;
        public static final int dialog_add_bookmark = 0x7f030006;
        public static final int search_item = 0x7f030007;
        public static final int seek_bar_preference = 0x7f030008;
    }

    public static final class menu {
        public static final int activity_about = 0x7f080000;
        public static final int activity_bookmarks = 0x7f080001;
        public static final int activity_books = 0x7f080002;
        public static final int activity_reading = 0x7f080003;
        public static final int activity_search = 0x7f080004;
        public static final int bookmark_list_menu = 0x7f080005;
    }

    public static final class string {
        public static final int app_name = 0x7f060000;
        public static final int hello_world = 0x7f060001;
        public static final int menu_about = 0x7f060002;
        public static final int add_bookmark = 0x7f060003;
        public static final int menu_add_bookmark = 0x7f060004;
        public static final int menu_bookmarks = 0x7f060005;
        public static final int bookmark_description = 0x7f060006;
        public static final int bookmark_type = 0x7f060007;
        public static final int dynamic = 0x7f060008;
        public static final int menu_settings = 0x7f060009;
        public static final int no_matches = 0x7f06000a;
        public static final int no_bookmarks = 0x7f06000b;
        public static final int ok = 0x7f06000c;
        public static final int cancel = 0x7f06000d;
        public static final int remove = 0x7f06000e;
        public static final int content_title = 0x7f06000f;
        public static final int display_title = 0x7f060010;
        public static final int pref_keep_awake = 0x7f060011;
        public static final int pref_keep_awake_summary = 0x7f060012;
        public static final int pref_purport = 0x7f060013;
        public static final int pref_purport_summary = 0x7f060014;
        public static final int pref_zoom = 0x7f060015;
        public static final int pref_zoom_summary = 0x7f060016;
        public static final int pref_reverse = 0x7f060017;
        public static final int pref_reverse_summary = 0x7f060018;
        public static final int pref_synonyms = 0x7f060019;
        public static final int pref_synonyms_summary = 0x7f06001a;
        public static final int pref_text = 0x7f06001b;
        public static final int pref_text_summary = 0x7f06001c;
        public static final int pref_translation = 0x7f06001d;
        public static final int pref_translation_summary = 0x7f06001e;
        public static final int search_hint = 0x7f06001f;
        public static final int title_activity_about = 0x7f060020;
        public static final int title_activity_bookmarks = 0x7f060021;
        public static final int title_activity_books = 0x7f060022;
        public static final int title_activity_reading = 0x7f060023;
        public static final int title_activity_search = 0x7f060024;
        public static final int title_activity_settings = 0x7f060025;
    }

    public static final class style {
        public static final int AppTheme = 0x7f070000;
    }

    public static final class xml {
        public static final int oldpreferences = 0x7f040000;
        public static final int preferences = 0x7f040001;
        public static final int searchable = 0x7f040002;
    }
}
